baseURL: https://lapacz-kornel.dev
title: Korneliusz Łapacz
params:
  author: Korneliusz Łapacz
  description: Kornel's homepage
  repo: https://github.com/kornellapacz/homepage
  mail: lapacz.kornel@gmail.com
menu:
  projects:
    - identifier: words
      name: Words
      url: https://kornellapacz.github.io/words
    - identifier: zeszyt
      name: Zeszyt
      url: https://zeszyt.lapacz-kornel.dev

  main:
    - identifier: github
      name: Github
      url: https://github.com/kornellapacz

languageCode: en
taxonomies:
  tag: tags
markup:
  highlight:
    noClasses: false
enableGitInfo: true # for lastmod date
