baseURL: https://lapacz-kornel.dev
title: Korneliusz Łapacz
params:
  author: Korneliusz Łapacz
  description: Kornel's homepage
  repo: https://github.com/kornellapacz/homepage
  mail: lapacz.kornel@gmail.com
menu:
  projects:
    - identifier: gmnigit
      name: gmnigit
      url: https://sr.ht/~kornellapacz/gmnigit/
    - identifier: words
      name: Words
      url: https://kornellapacz.github.io/words
    - identifier: zeszyt
      name: Zeszyt
      url: https://zeszyt.lapacz-kornel.dev

  main:
    - identifier: github
      name: Github
      url: https://github.com/kornellapacz
    - identifier: sourcehut
      name: Sourcehut
      url: https://sr.ht/~kornellapacz

languageCode: en
taxonomies:
  tag: tags
markup:
  highlight:
    noClasses: false
enableGitInfo: true # for lastmod date
